theme = "onedark"

[keys.insert]
j = { j = "normal_mode" }


[keys.normal]
g = { j = "move_line_down" }

[editor.statusline]
left = ["mode", "file-name", "spinner"]
right = ["file-type", "selections", "position"]
